name: patient-manager
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - minio
    volumes:
      - ./backend:/api
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  mysql:
    image: mysql:latest
    container_name: patient-manager-db
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  minio:
    image: "minio/minio:latest"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090"
    env_file:
      - ./backend/.env
    volumes:
      - "minio:/data/minio"
    command: minio server /data/minio --console-address ":9090"
volumes:
  db_data:
    driver: local
  minio:
    driver: local
